
steps:
  - name: 'node:14'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node:14'
    entrypoint: 'npm'
    args: ['test']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'helloWorld', '--runtime', 'nodejs14', '--trigger-http']
